name: ${project.artifactId}
version: ${project.version}
main: nl.tabuu.permissionshopz.PermissionShopZ
description: ${project.description}
authors: [Tabuu]
website: https://www.tabuu.nl
depend: [Vault, TabuuCore]
softdepend: [GroupManager, PermissionsEx, LuckPerms]
api-version: '1.13'

commands:
  permissionshopz:
    usage: /permissionshopz
    description: Opens the shop.
    permission: permissionshopz.default
    aliases: [pshop, permissionshop]

  permissionshopz add:
    usage: /permissionshopz add
    description: Creates a new perk and opens the edit window for that perk.
    permission: permissionshopz.admin

  permissionshopz edit:
    usage: /permissionshopz edit
    description: Opens the shop editor.
    permission: permissionshopz.admin

  permissionshopz debuginfo:
    usage: /permissionshopz debuginfo
    description: Displays information about the current state of the plugin.
    permission: permissionshopz.admin

  permissionshopz reload:
    usage: /permissionshopz reload
    description: Reloads the config.
    permission: permissionshopz.admin

  permissionshopz loaddata:
    usage: /permissionshopz loaddata
    description: Loads the data from config.
    permission: permissionshopz.admin


  permissionshopz cleandata:
    usage: /permissionshopz cleandata
    description: Removes all unused data from the database.
    permission: permissionshopz.admin

permissions:
  permissionshopz.default:
    description: Allows players to open the GUI.
    default: true

  permissionshopz.admin:
    description: Allows players to manage the permission shop.
    default: op